server:
  port: 8182
  forward-headers-strategy: framework
spring:
  datasource:
    hikari:
      maximum-pool-size: 50
      connection-timeout: 6000
    url: jdbc:postgresql://postgres:5432/highload
    username: high_user
    password: high_user
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
jwt:
  secret: ${JWT_SECRET}
  expired: ${JWT_EXPIRED}
pagination:
  maxSize: ${PAGINATION_MAX_SIZE}
resilience4j.circuitbreaker:
  instances:
    userServiceBreaker:
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 10s
      failureRateThreshold: 40
    loginServiceBreaker:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
    orderServiceBreaker:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
    imageServiceBreaker:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
management:
  endpoints:
    web:
      exposure:
        include: '*'

