server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: login-service
          uri: lb://login-service
          predicates:
            - Path=/api/auth/login, /api/auth/validate, /api/auth/get-login-from-token
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/api/image/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/profile/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/