server:
  port: 8180
  forward-headers-strategy: framework
spring:
  security:
    basic:
      enable: false
    ignored: /**
  datasource:
    hikari:
      maximum-pool-size: 50
      connection-timeout: 6000
    url: jdbc:postgresql://postgres:5432/highload
    username: high_user
    password: high_user
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
jwt:
  secret: ${JWT_SECRET}
  expired: ${JWT_EXPIRED}
pagination:
  maxSize: ${PAGINATION_MAX_SIZE}

springdoc:
  swagger-ui:
    use-root-path: true

management:
  endpoints:
    web:
      exposure:
        include: '*'