server:
  port: 8183
  forward-headers-strategy: framework
spring:
  kafka:
    consumer:
      group-id=response:
    template:
      default-topic=notifications:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: kafka:29092
  datasource:
    hikari:
      maximum-pool-size: 50
      connection-timeout: 6000
    url: jdbc:postgresql://postgres:5432/highload
    username: high_user
    password: high_user
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
eureka:
  client:
    serviceUrl:
      #defaultZone: http://eureka:8761/eureka/
      defaultZone: http://eureka:8761/eureka/
jwt:
  secret: ${JWT_SECRET}
  expired: ${JWT_EXPIRED}
pagination:
  maxSize: ${PAGINATION_MAX_SIZE}
resilience4j.circuitbreaker:
  instances:
    userServiceBreaker:
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 10s
      failureRateThreshold: 40
    loginServiceBreaker:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
management:
  endpoints:
    web:
      exposure:
        include: '*'

